const CSS = `
  * {
    font-family: "Lato", sans-serif;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  body {
    width: 100svw;
    height: 100svh;
  }

  main {
    display: flex;
    flex-direction: column;
    padding: 2rem;
    gap: 2rem;
    width: 100%;
    height: 100%;
    overflow: auto;
  }

  .name-wrapper {
    display: flex;
    flex-direction: column;
  }

  .subsection {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .first-name,
  .last-name,
  .role {
    font-size: 78pt;
    font-weight: 900;
    text-transform: uppercase;
  }

  .last-name {
    margin-top: -2rem;
  }

  .role {
    font-size: 32pt;
  }

  a {
    text-decoration: none;
    color: oklch(0.705 0.015 286.067);
  }

  a:hover {
    color: black;
  }

  .links {
    display: flex;
    gap: 0.75rem;
    margin-top: 0.75rem;
    margin-bottom: 0.25rem;
  }

  .link {
    font-size: 16pt;
  }

  .info-description,
  .subsection-title {
    font-size: 20pt;
  }

  .subsection-title {
    font-weight: 900;
    text-transform: uppercase;
  }

  .infos {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .info {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    border: 0.1rem rgba(0, 0, 0, 0.2) solid;
    padding: 1rem;
    border-radius: 1rem;
  }

  .info-title {
    font-size: 16pt;
  }

  .info-subtitle {
    font-weight: 300;
    font-size: 11pt;
  }

  .technologies {
    display: flex;
    gap: 0.25rem;
    margin-top: 0.5rem;
  }

  .technology {
    background-color: black;
    color: white;
    padding: 0.25rem 0.5rem;
    border-radius: 100px;
    font-size: 9pt;
  }

  .footer {
    font-size: 9pt;
  }

  @media (max-width: 645px) {
    .first-name,
    .last-name {
      font-size: 42pt;
    }

    .last-name {
      margin-top: -1rem;
    }

    .role {
      font-size: 20pt;
    }

    .info-description,
    .subsection-title {
      font-size: 16pt;
    }

    .info-title {
      font-size: 12pt;
    }
  }
`;

export const HTML = `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <style>${CSS}</style>
  </head>
  <body>
    <main>
      <div class="name-wrapper">
        <span class="first-name">{firstName}</span>
        <span class="last-name">{lastName}</span>
        <span class="role">{role}</span>
        <div class="links">
          <a
            class="link"
            href="{gitHub}"
            target="_blank"
          >
            GitHub
          </a>
          <a
            class="link"
            href="{linkedIn}"
            target="_blank"
          >
            LinkedIn
          </a>
        </div>
      </div>
      <div class="subsection">
        <span class="subsection-title">About me</span>
        <div class="infos">
          <div class="info">
            <span class="info-title">Location</span>
            <span class="info-description">{location}</span>
          </div>
        </div>
      </div>
      <div class="subsection">
        <span class="subsection-title">Contact</span>
        <div class="infos">
          <div class="info">
            <span class="info-title">Email</span>
            <div>
              <a
                class="info-description"
                href="mailto:{email}"
              >
                {email}
              </a>
            </div>
          </div>
          <div class="info">
            <span class="info-title">Number</span>
            <div>
              <a
                class="info-description"
                href="https://wa.me/{number}"
                target="_blank"
              >
                {number}
              </a>
            </div>
          </div>
        </div>
      </div>
      {language}
      {experience}
      {education}
      {project}
      {setup}
      <span class="footer">Generated by
        <a
          href="https://prezentme.vercel.app"
          target="_blank"
        >
          PrezentMe
        </a>
        ©
        <a
          href="https://github.com/richardqcarvalho/prezentme"
          target="_blank"
        >
          Richard Carvalho
        </a>
      </span>
    </main>
  </body>
</html>
`;
